// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTER_H_
#define FLATBUFFERS_GENERATED_MONSTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct Weapon;
struct WeaponBuilder;

struct Monster;
struct MonsterBuilder;

enum Grade : int8_t {
  Grade_normal = 0,
  Grade_magic = 1,
  Grade_rare = 2,
  Grade_unique = 3,
  Grade_MIN = Grade_normal,
  Grade_MAX = Grade_unique
};

inline const Grade (&EnumValuesGrade())[4] {
  static const Grade values[] = {
    Grade_normal,
    Grade_magic,
    Grade_rare,
    Grade_unique
  };
  return values;
}

inline const char * const *EnumNamesGrade() {
  static const char * const names[5] = {
    "normal",
    "magic",
    "rare",
    "unique",
    nullptr
  };
  return names;
}

inline const char *EnumNameGrade(Grade e) {
  if (::flatbuffers::IsOutRange(e, Grade_normal, Grade_unique)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGrade()[index];
}

struct Weapon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WeaponBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DAMAGE = 6,
    VT_GRADE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float damage() const {
    return GetField<float>(VT_DAMAGE, 0.0f);
  }
  Grade grade() const {
    return static_cast<Grade>(GetField<int8_t>(VT_GRADE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_DAMAGE, 4) &&
           VerifyField<int8_t>(verifier, VT_GRADE, 1) &&
           verifier.EndTable();
  }
};

struct WeaponBuilder {
  typedef Weapon Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Weapon::VT_NAME, name);
  }
  void add_damage(float damage) {
    fbb_.AddElement<float>(Weapon::VT_DAMAGE, damage, 0.0f);
  }
  void add_grade(Grade grade) {
    fbb_.AddElement<int8_t>(Weapon::VT_GRADE, static_cast<int8_t>(grade), 0);
  }
  explicit WeaponBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Weapon> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Weapon>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Weapon> CreateWeapon(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float damage = 0.0f,
    Grade grade = Grade_normal) {
  WeaponBuilder builder_(_fbb);
  builder_.add_damage(damage);
  builder_.add_name(name);
  builder_.add_grade(grade);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Weapon> CreateWeaponDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float damage = 0.0f,
    Grade grade = Grade_normal) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateWeapon(
      _fbb,
      name__,
      damage,
      grade);
}

struct Monster FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MonsterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_HEALTH = 6,
    VT_WEAPONS = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t health() const {
    return GetField<int32_t>(VT_HEALTH, 0);
  }
  const Weapon *weapons() const {
    return GetPointer<const Weapon *>(VT_WEAPONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_HEALTH, 4) &&
           VerifyOffset(verifier, VT_WEAPONS) &&
           verifier.VerifyTable(weapons()) &&
           verifier.EndTable();
  }
};

struct MonsterBuilder {
  typedef Monster Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Monster::VT_NAME, name);
  }
  void add_health(int32_t health) {
    fbb_.AddElement<int32_t>(Monster::VT_HEALTH, health, 0);
  }
  void add_weapons(::flatbuffers::Offset<Weapon> weapons) {
    fbb_.AddOffset(Monster::VT_WEAPONS, weapons);
  }
  explicit MonsterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Monster> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Monster>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Monster> CreateMonster(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t health = 0,
    ::flatbuffers::Offset<Weapon> weapons = 0) {
  MonsterBuilder builder_(_fbb);
  builder_.add_weapons(weapons);
  builder_.add_health(health);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Monster> CreateMonsterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t health = 0,
    ::flatbuffers::Offset<Weapon> weapons = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return CreateMonster(
      _fbb,
      name__,
      health,
      weapons);
}

inline const Monster *GetMonster(const void *buf) {
  return ::flatbuffers::GetRoot<Monster>(buf);
}

inline const Monster *GetSizePrefixedMonster(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Monster>(buf);
}

template <bool B = false>
inline bool VerifyMonsterBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Monster>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMonsterBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Monster>(nullptr);
}

inline void FinishMonsterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Monster> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonsterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Monster> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MONSTER_H_
